import {
  Home,
  Info,
  ShoppingBag,
  Weight,
  Phone,
  FileText,
  Lock,
  Truck,
  RotateCcw,
} from "lucide-react";

export const NAV_LINKS = [
  {
    id: "home",
    label: "Home",
    href: "/",
    isDesktop: false,
    isExternal: false,
    type: "primary",
    icon: Home,
  },
  {
    id: "about",
    label: "About",
    href: "/#about-us",
    isDesktop: true,
    isExternal: false,
    type: "primary",
    icon: Info,
  },
  {
    id: "products",
    label: "Products",
    href: "/products",
    isDesktop: true,
    isExternal: false,
    type: "primary",
    icon: ShoppingBag,
  },
  {
    id: "kettlebell",
    label: "The Kettlebell",
    href: "/the-kettlebell",
    isDesktop: true,
    isExternal: false,
    type: "primary",
    icon: Weight,
  },
  {
    id: "contact",
    label: "Contact",
    href: "/contact",
    isDesktop: true,
    isExternal: false,
    type: "primary",
    icon: Phone,
  },

  // secondary nav (legal pages)
  {
    id: "terms",
    label: "Terms & Conditions",
    href: "/legal/terms-and-conditions",
    isDesktop: false,
    isExternal: false,
    type: "secondary",
    icon: FileText,
  },
  {
    id: "privacy",
    label: "Privacy Policy",
    href: "/legal/privacy-policy",
    isDesktop: false,
    isExternal: false,
    type: "secondary",
    icon: Lock,
  },
  {
    id: "shipping",
    label: "Shipping & Delivery",
    href: "/legal/shipping-and-delivery",
    isDesktop: false,
    isExternal: false,
    type: "secondary",
    icon: Truck,
  },
  {
    id: "returns",
    label: "Refunds & Returns",
    href: "/legal/refunds-and-returns",
    isDesktop: false,
    isExternal: false,
    type: "secondary",
    icon: RotateCcw,
  },
];
